version: 2
jobs:
  setup_dependencies:
    docker:
      - image: circleci/python3.8.1
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "requirements.lock" }}
      - run:
          command: |
            pip instal l --user -r requirements.lock
      - save_cache:
          key: deps-{{ checksum "requirements.lock }}
          paths:
            - "~/.local"

  test:
    docker:
      - image: circleci/python3.8.1
    steps:
      - checkout
      - restore_cache:
          key deps-{{ checksum "requirements.lock" }}
      - run:
          command: |
            python3 -m unittest -v
workflows:
  version: 2
  all:
    jobs:
      - setup_dependencies
      - test:
          requires:
            - setup_dependencies